add section about-us
HannaPalianytsia/first-team-project pull request #2
Opened 2023-11-03 17:55 UTC by ChernyshovVadym

Зробив скелет сайту, та добавив css

2023-11-03 21:19 UTC, HannaPalianytsia requested changes

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/img/Rectangle.jpg
перенеси в папку about всередині img і відповідно зміни шлях в about.html

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/img/Rectangle@2x-min.jpg
тут так само як з попереднім зорбраженням: перенеси в папку about всередині img і відповідно зміни шлях в about.html

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/partials/about.html
> +<section class="about-us">
додай id до секції і відправ його Сергію і Юлі, вони будуть робити якірні посилання на секції `<section class="about-us" id="....">`

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/partials/about.html
> +    <div class="container">
div container треба тільки один в секції. структура буде така: 
`<section class="about-us">
    <div class="container">
    <h2></h2>
    <img src="" alt="">
    <p></p>
    <p></p>
</div>
</section>`
тобто для кожного тега не потрібен контейнер

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/partials/about.html
> +        <a href="./about.html">
тут не потрібне посилання, просто заголовок

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/partials/about.html
> +            src="../img/Rectangle.jpg" alt="Rectangle" width="209">
тут треба забрати width="209". ширину треба буде прописати в css. для кожного пристрою вона буде різною

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +    width: 335px;
ширину секції не потрібно задавати. в нас прописана загальна ширина для контейнера

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +    display: inline-flex;
флекс тут теж треба буде видалити. він не спрацює, коли обгорнеш всередині секції зробиш загальний контейнер дівом

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +    gap: 40px;
плюс цей геп робить відступи по 40, а між абзацами в тебе має бути відступ 20

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +    display: flex;
для зображення флекс не потрібен, усі зображення в нас блокові

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +    display: flex;
для параграфів також не потрібен флекс

2023-11-03 21:19 UTC, HannaPalianytsia commented on src/css/about.css
> +}
і потрібно додати медіа

2023-11-03 21:21 UTC, HannaPalianytsia commented on src/partials/about.html
> +    <div class="container">
<img width="335" alt="image" src="https://github.com/HannaPalianytsia/first-team-project/assets/28064064/bdfe4f74-9489-4048-85bd-9dd1f36d5c14">

2023-11-06 13:36 UTC, ChernyshovVadym commented on src/partials/about.html
> +<section class="about-us">
добавив

2023-11-06 13:40 UTC, ChernyshovVadym commented on src/partials/about.html
> +            src="../img/Rectangle.jpg" alt="Rectangle" width="209">
так вірно же, вона не дає змоги фото заходити за контейнер?.. чи ні!?..

2023-11-06 13:43 UTC, ChernyshovVadym commented on src/css/about.css
> +    width: 335px;
видалив, дякую, так дійсно на багато краще!

2023-11-06 13:45 UTC, ChernyshovVadym commented on src/css/about.css
> +    display: inline-flex;
та ні, не згоден флекс як раз і тримає зліва картинку і текст в секціях

2023-11-06 13:45 UTC, ChernyshovVadym commented on src/css/about.css
> +    gap: 40px;
переробив

2023-11-06 13:47 UTC, ChernyshovVadym commented on src/css/about.css
> +    display: flex;
тут згоден! він зайвий, дякую

2023-11-06 18:52 UTC, ChernyshovVadym commented on src/css/about.css
> +}
ок

2023-11-06 19:24 UTC, ChernyshovVadym commented on src/css/about.css
> +    display: flex;
зробив! дякую

2023-11-07 09:12 UTC, ChernyshovVadym commented
все таки не розумію чому фото не працюють?..

2023-11-07 14:25 UTC, HannaPalianytsia approved these changes

2023-11-07 14:25 UTC, merged