Sign up
HannaPalianytsia/first-team-project pull request #5
Opened 2023-11-04 11:58 UTC by valiana35

2023-11-05 14:13 UTC, serg444s commented on src/css/signup.css
> +    text-transform: uppercase;
border: none;

2023-11-05 14:13 UTC, serg444s commented on src/css/signup.css
> +        max-width: 280px;
295px

2023-11-05 14:24 UTC, serg444s commented on src/css/signup.css
> +        max-width: 430px;
480px

2023-11-05 14:24 UTC, serg444s commented on src/css/signup.css
> +        max-width: 430px;
480px

2023-11-05 14:34 UTC, serg444s commented on src/css/signup.css
> +        max-width: 375px;
335px

2023-11-05 15:57 UTC, valiana35 commented on src/css/signup.css
> +    text-transform: uppercase;
Дякую, виправила

2023-11-05 15:58 UTC, valiana35 commented on src/css/signup.css
> +        max-width: 375px;
кнопка виходить замала, не як на макеті

2023-11-06 16:08 UTC, HannaPalianytsia requested changes

2023-11-06 16:08 UTC, HannaPalianytsia commented on src/partials/signup.html
> +        <a href="">Privacy Policy</a>, and allow Promodo to use this information
після Privacy Policy треба додати br після коми

2023-11-06 16:43 UTC, HannaPalianytsia commented on src/css/signup.css
> +        max-width: 430px;
width: 480px;

2023-11-06 16:44 UTC, HannaPalianytsia commented on src/css/signup.css
> +        max-width: 280px;
width: 295px;

2023-11-06 16:44 UTC, HannaPalianytsia commented on src/css/signup.css
> +        max-width: 430px;
width: 480px;

2023-11-06 19:01 UTC, HannaPalianytsia approved these changes

2023-11-06 19:01 UTC, merged